name: .NET Tests & Auto-commit

on:
  pull_request_target:          # безопасное событие для кода из форка
    types: [opened, synchronize, reopened]
  push:
    branches-ignore: [main]     # при пушах в ветки, кроме main
  workflow_dispatch:            # ручной запуск
  issue_comment:                # запуск по комментарию

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:

  check-target:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - name: 🚫 Проверка PR в main
        shell: bash
        run: |
          BASE_REF="${{ github.event.pull_request.base.ref || github.event.pull_request.base?.ref }}"
          echo "Base branch: $BASE_REF"
          if [ "$BASE_REF" = "main" ]; then
            echo "❌ Нельзя отправлять работу в main ветку."
            exit 1
          else
            echo "✅ PR направлен в '$BASE_REF', можно запускать тесты."
          fi

  tests:
    name: Run test
    runs-on: windows-latest
    needs: [check-target]
    if: |
      (github.event_name == 'pull_request_target' && needs.check-target.result == 'success') ||
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'issue_comment'
    strategy:
      matrix:
        configuration: [Debug]

    steps:
    - name: Checkout PR code safely
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore
      run: dotnet restore Lab2/Lab2.sln

    - name: Build
      run: dotnet build Lab2/Lab2.sln --configuration ${{ matrix.configuration }} --no-restore

    - name: Run tests (Purple→Blue→Green→White)
      id: cascade
      shell: pwsh
      run: |
        $colors = @('Purple', 'Blue', 'Green', 'White')
        foreach ($c in $colors) {
          Write-Host "🔎  Запуск тестов класса $c"
          dotnet test Lab2test/Lab2test.csproj `
            --filter "FullyQualifiedName~$c" `
            --configuration $Env:CFG `
            --no-build `
            --logger "trx;LogFileName=test-$c.trx"
          if ($LASTEXITCODE -eq 0) {
            Write-Host "✅  Класс $c прошёл. Останавливаем каскад."
            exit 0
          }
        }
        Write-Host "❌  Ни один класс не прошёл."
        exit 1
      env:
        CFG: ${{ matrix.configuration }}

    - name: Upload TRX
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: trx-${{ matrix.configuration }}
        path: '**/test-results.trx'
